trigger:
- main

pool:
  name: 'WKL-rwbuvlczft6004564'  # Specifies the self-hosted agent pool

steps:
- script: |
    # Install Python 3.11 if not installed
    sudo apt install python3
  displayName: 'Install Python 3.11 if not present'


- script: |
    python3 test.py  # Run python File
  displayName: 'Run test.py'
