name: CI/CD Deploy on Commit (Self-Hosted)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login offensivewebapp.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Pull latest base image
        run: docker pull offensivewebapp.azurecr.io/malicious-image:latest

      - name: Stop existing container (if running)
        run: |
          docker stop malicious-webapp || true
          docker rm malicious-webapp || true

      - name: Deploy updated container with mounted code
        run: |
          docker run -d \
            --name malicious-webapp \
            -v ${{ github.workspace }}:/app \
            -p 8080:80 \
            offensivewebapp.azurecr.io/malicious-image:latest

      - name: Health check on running container
        run: |
          sleep 5
          curl -s http://localhost:8080 || echo "App may not be fully up"
