name: Vulnerable PR Workflow
on:
  pull_request_target

jobs:
  insecure-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Leak secrets
        run: echo "SECRET_LEAKED ${{ secrets.SEC_NAME }}"

      - name: List Env
        run: env
        
      - name: Run build
        run: echo "Building the project for branch ${{ github.event.pull_request.head.ref }}"
