name: Deploy Malicious Image

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login offensivewebapp.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Pull malicious image
        run: docker pull offensivewebapp.azurecr.io/malicious-image:latest

      - name: Run container from image
        run: docker run -d --name malicious-container -p 8080:80 offensivewebapp.azurecr.io/malicious-image:latest

      - name: Simulate deployment step
        run: curl http://localhost:8080 || echo "Simulated check app may not respond here in CI"
