name: "CI/CD: Build, Push, and Deploy via ACR"

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_REGISTRY }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build Docker image from repo
        run: |
          docker build -t ${{ secrets.ACR_REGISTRY }}/malicious-image:${{ github.sha }} .
          docker tag ${{ secrets.ACR_REGISTRY }}/malicious-image:${{ github.sha }} ${{ secrets.ACR_REGISTRY }}/malicious-image:latest

      - name: Push Docker image to ACR
        run: |
          docker push ${{ secrets.ACR_REGISTRY }}/malicious-image:${{ github.sha }}
          docker push ${{ secrets.ACR_REGISTRY }}/malicious-image:latest

      - name: Stop existing container (if running)
        run: |
          docker stop malicious-webapp || true
          docker rm malicious-webapp || true

      - name: Deploy updated container
        run: |
          docker pull ${{ secrets.ACR_REGISTRY }}/malicious-image:latest
          docker run -d \
            --name malicious-webapp \
            -p 8080:80 \
            ${{ secrets.ACR_REGISTRY }}/malicious-image:latest

      - name: Health check
        run: |
          sleep 5
          curl -s http://localhost:8080 || echo "App may not be up"
